name: Build base

on:
  workflow_dispatch:

env:
  JUPYTERHUB_VERSION: hub-5.2.1
  TAG: $JUPYTERHUB_VERSION-$(date +'%Y-%m-%d')
  REPO: harbor.stfc.ac.uk/biosimulation-cloud
  IMAGE_NAME: biosim-jupyter-base

jobs:
  build:
    runs-on: ubuntu-24.04
    name: base-build
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          echo $TAG
          echo $REPO
          echo $IMAGE_NAME
          docker build . --build-arg BASE_IMAGE=${{ env.JUPYTERHUB_VERSION }} -t $REPO/$IMAGE_NAME:$TAG -t $REPO/$IMAGE_NAME:latest

      - name: Authenticate with harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Push image to Harbor
        run: |
          docker push --all-tags $REPO/$IMAGE_NAME

  trigger:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        repos: ["basic-analysis", "basic-statistics", "clustering", "equilibration", "pca", "pdb2pqr", "python", "qmmm", "structure-validation", "ubiquitin-analysis"]
    name: jupyterhub-${{ matrix.jupyter-base }}
    steps:  
      - name: Repository Dispatch Build Trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          repository: jimboid/biosim-${{ matrix.repos }}-workshop
          event-type: build    
          client-payload: '{"tag": "$TAG"}'

