name: Build and Push containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        jupyter-base: [5.2.1]
    name: jupyterhub-${{ matrix.jupyter-base }}
    steps:
      - name: Authenticate with harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: actions/checkout@v4

      - name: Build container
        run: |
          docker build . --build-arg BASE_IMAGE=hub-${{ matrix.jupyter-base }} -t harbor.stfc.ac.uk/biosimulation-cloud/biosim-jupyter-base:hub-${{ matrix.jupyter-base }}-$(date +'%Y-%m-%d')

      - name: Push image to Harbor
        run: |
          docker push harbor.stfc.ac.uk/biosimulation-cloud/biosim-jupyter-base:hub-${{ matrix.jupyter-base }}-$(date +'%Y-%m-%d')

  trigger:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        repos: ["basic-analysis", "basic-statistics", "clustering", "equilibration", "pca", "pdb2pqr", "python", "qmmm", "structure-validation", "ubiquitin-analysis"]
    name: jupyterhub-${{ matrix.jupyter-base }}
    steps:  
      - name: Repository Dispatch Build Trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          repository: jimboid/biosim-${{ matrix.repos }}-workshop
          event-type: build    
          client_payload: {"tag": "hub-5.2.1-$(date +'%Y-%m-%d')"}

