name: build
on:
  workflow_dispatch:

env:
  JUPYTERHUB_VERSION: "hub-5.2.1"
  REGISTRY: "ghcr.io"
  REPO: "jimboid"
  IMAGE_NAME: "biosim-jupyter-base"

jobs:
  build:
    runs-on: ubuntu-24.04
    name: base-build
    outputs:
      tag: ${{ steps.envvars.outputs.tag }}
      path: ${{ steps.envvars.outputs.path }}
    steps:
      - uses: actions/checkout@v4

      - name: Set env vars
        id: envvars
        run: |
          TAG="${{ env.JUPYTERHUB_VERSION }}-$(date +'%Y-%m-%d')"
          PATH="${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}"
          echo "path=${PATH}" >> "$GITHUB_OUTPUT"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo ${PATH}
          echo ${TAG}

      - name: Build image
        id: build
        run: |
          docker build . \
          --build-arg BASE_IMAGE=${{ env.JUPYTERHUB_VERSION }} \
          -t ${{ steps.envvars.outputs.path }}:${{ steps.envvars.outputs.tag }} \
          -t ${{ steps.envvars.outputs.path }}:latest

      - name: Authenticate with GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.BUILD_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker push --all-tags ${{ steps.envvars.outputs.path }}

  trigger:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        repos: ["aiida-gpcr",
                "aiida-lysozyme",
                "basic-analysis",
                "basic-statistics",
                "beginners",
                "clustering",
                "codeentropy",
                "docking",
                "enhanced-sampling",
                "equilibration",
                "introamber",
                "nemd",
                "openff",
                "pca",
                "pdb2pqr",
                "python",
                "qmmm",
                "structure-validation",
                "ubiquitin-analysis"]
    name: jupyterhub-${{ matrix.jupyter-base }}
    steps:  
      - name: Repository Dispatch Build Trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          repository: jimboid/biosim-${{ matrix.repos }}-workshop
          event-type: build    
          client-payload: '{"tag": "${{ needs.build.outputs.tag }}"}'

