name: release

on:
  repository_dispatch:
    types: [release]

jobs:
  tag-release:
    runs-on: ubuntu-24.04
    name: release process
    needs:
      - tests
    steps:
      - name: Authenticate with GHCR
        id: auth
        uses: docker/login-action@v3.5.0
        with:
          registry: "ghcr.io"
          username: ${{github.actor}}
          password: ${{secrets.BUILD_TOKEN}}

      - name: Push new tags
        shell: bash
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ github.event.client_payload.tag }} \
            ghcr.io/${{ github.repository }}:dev.tested

#  triggers:
#    runs-on: ubuntu-24.04
#    strategy:
#      matrix:
#        repos: ["aiida-gpcr-workshop",
#                "aiida-lysozyme-workshop",
#                "basic-analysis-workshop",
#                "basic-statistics-workshop",
#                "beginners-workshop",
#                "clustering-workshop",
#                "codeentropy-workshop",
#                "docking-workshop",
#                "enhanced-sampling-workshop",
#                "equilibration-workshop",
#                "introamber-workshop",
#                "nemd-workshop",
#                "openff-workshop",
#                "pca-workshop",
#                "pdb2pqr-workshop",
#                "python-workshop",
#                "qmmm-workshop",
#                "structure-validation-workshop",
#                "ubiquitin-analysis-workshop"]
#    name: jupyterhub-${{ matrix.jupyter-base }}
#    steps:  
#      - name: Trigger to build workshops
#        uses: peter-evans/repository-dispatch@v3.0.0
#        with:
#          token: ${{ secrets.BUILD_TOKEN }}
#          repository: jimboid/biosim-${{ matrix.repos }}
#          event-type: build    
#          client-payload: '{"tag": "${{ github.event.client_payload.tag }}"}'
